examples/identity/keycloak_token_exchange/README.md
examples/identity/keycloak_token_exchange/custom_keycloak.md
examples/identity/keycloak_token_exchange/resources/cluster/kind_cluster_config.yaml
examples/identity/keycloak_token_exchange/resources/cluster/kind_ingress_deployment.yaml
examples/identity/keycloak_token_exchange/resources/keycloak/ingress.yaml
examples/identity/keycloak_token_exchange/resources/keycloak/namespace.yaml
examples/identity/keycloak_token_exchange/resources/keycloak/service.yaml
examples/identity/keycloak_token_exchange/resources/keycloak/statefulset.yaml
examples/identity/keycloak_token_exchange/resources/spire/client/Dockerfile
examples/identity/keycloak_token_exchange/resources/spire/client/helper.conf
examples/identity/keycloak_token_exchange/resources/spire/helm_values.yaml
examples/identity/keycloak_token_exchange/resources/spire/oidc-ingress-http.yaml
examples/identity/keycloak_token_exchange/resources/spire/workload_agent.yaml
examples/identity/keycloak_token_exchange/resources/spire/workload_api.yaml

Added Keycloak + SPIRE example under examples/identity

Add identity demos

---

examples/identity/keycloak_token_exchange/README.md
examples/identity/keycloak_token_exchange/demo_keycloak_config.py
examples/identity/keycloak_token_exchange/keycloak_wrapper.py
examples/identity/keycloak_token_exchange/requirements.txt

Add script for configuring KeyCloak in the KeyCloak token exchange demo.

Add KeyCloak config demo script

---

docs/cn-pocs.md
examples/templates/a2a/a2a-contact-extractor-agent.yaml
examples/templates/a2a/a2a-currency-agent.yaml
examples/templates/acp/acp-ollama-researcher.yaml

add example templates for agents deployment

feat: add example templates for agents deployment

---

examples/templates/a2a/a2a-contact-extractor-agent.yaml
examples/templates/acp/acp-ollama-researcher.yaml

add cleanupAfterBuild to example templates

fix: add cleanupAfterBuild to example templates

---

examples/mcp/Dockerfile

fix: fix mcp example dockerfile

---

examples/clients/acp/agent.py
examples/clients/acp/client.py
examples/clients/acp/pyproject.toml
examples/clients/acp/uv.lock
examples/templates/acp/acp-ollama-researcher.yaml

add ACP client based on ACP SDK

feat: add ACP client based on ACP SDK

---

CONTRIBUTING.md
README.md
docs/demos.md
docs/tech-details.md

Rename PoC to components and demos

Change PoC to demo

---

README.md
docs/cn-demos.md
docs/tech-details.md

fix: fix typos in docs

---

docs/cn-demos.md
kagenti/installer/src/installer.py

Some information requires minor updates. 
The required versions don't match the most recent install. We probably need to remove the max values. My podman has a different versioning than docker.

Update install documentation

---

kagenti/installer/app/components/gateway.py
kagenti/installer/app/utils.py

fix issue with trying to check status of non-existing deployment
Fixes: #39

fix: fix issue with trying to check status of non-existing deployment

---

kagenti/installer/app/components/agents.py
kagenti/installer/app/linux/ollama-config.sh

Fixes path for custom linux config
xref: #80

:bug: fix path for linux custom install options

---

kagenti/ui/pages/04_Import_New_Agent.py

🌱 start removing ACP from UI

---

kagenti/installer/app/cli.py
kagenti/installer/app/cluster.py

Allows for `uv run kagenti-installer --silent` without user intervention
Fixes #87

:seedling::wrench: Allow for --silent installation

---

docs/demo-weather-agent.md
docs/demos.md

Updating the docs based on the updates to my latest installation from https://github.com/kagenti/agent-examples
Relates to #145

:book: Update weather demo docs

---

docs/demos.md
kagenti/installer/app/resources/keycloak.yaml

More settings for Keycloak deployment

🐛 more keycloak fixes

---

docs/demos.md
kagenti/installer/app/components/keycloak.py
kagenti/installer/app/resources/ui-oauth-secret.yaml

At this time there is no reliable sequence of bringing down and up again
postgres and keycloak. The only reliable approach found so far is either to destroy and re-install
the cluster or delete and re-install keycloak.
Fixes #115

🌱 add instructions and commands to repair broken keycloak

---

deployments/ui/kagenti-ui.yaml
kagenti/ui/Dockerfile

Allowing non-root user and emptyDIrs for caches to allow this to be ran on openshift
Part of #153 
Fixes #

✨ UI changes for openshift

---

kagenti/installer/app/components/keycloak.py

Linter did not successfully ran after broken reference was introduced by #155. This PR corrects the issue.

🐛 fix linter broken by #155

---

kagenti/installer/app/resources/phoenix.yaml

Persistent storage for postgres
Part of #153 
Fixes #

✨ persistent storage for postgres for OCP usage

---

docs/demos.md
kagenti/ui/lib/build_utils.py

Updates agent rollover instructions when keycloak stops working
Builds on additions in #166

:book: Update keycloak stops working steps with agent rollover

---

.github/workflows/build.yaml

Refactors multiple Docker images into build matrix - following https://github.com/kagenti/agent-examples/blob/main/.github/workflows/build.yaml per suggested in the issue
Fixes #183

:seedling::recycle: Refactor build into matrix

---

README.md
docs/demo-slack-research-agent/README.md
docs/demos.md

Some updates to Slack Demo documenation
Fixes #

:book: Update Slack demo documenation

---

docs/demo-slack-research-agent/README.md

Added more details to the Slack demo documentation
Some edits based on suggestions from @huang195

📖 Add more details to the Slack documentation

---

docs/dev-guide.md
kagenti/ui/scripts/ui-dev-build.sh

Add developer's docs to work on UI
Fixes #144

📖  add UI dev instructions

---

docs/demo-slack-research-agent/README.md

Update slack demo README for further information on models

Update slack demo README

---

docs/gateway.md

Documentation that describe how tools are registered with the Gateway and how agents can access these tools via the Gateway.

update gateway doc

---

kagenti/installer/app/components/keycloak.py

skip initial keycloak setup for existing cluster

🐛 skip initial keycloak setup for existing cluster

---

.github/dockerfiles/postgres/Dockerfile
.github/dockerfiles/python12/Dockerfile
.github/workflows/build-dependency-images.yml

add action and dockerfile to build deps images

🌱 add action and dockerfile to build deps images

---

CONTRIBUTING.md

Update the Contributing doc with a reference to Developer's Guide and some formatting.
Fixes #

:book Update Contributing documentation

---

docs/ocp/openshift-install.md

Add instructions to update chart dependencies for Kagenti chart.

📖 add instructions to update Kagenti helm chart dependencies

---

.github/workflows/build.yaml

Fixes CI to update deps for helm chart publishing

🐛 update deps for helm chart publishing

---

.github/workflows/build.yaml

🐛 fix chart name in CI

---

docs/demo-weather-agent.md

- Installation doc reference was broken
- Auth references were removed partially in #222 - this removes references to the section
- Somewhat make spacing more consistent among console logs

📖 Update weather agent demo docs

---

kagenti/auth/client-registration/client_registration.py
kagenti/ui/lib/tool_details_page.py

- Linting for UI was failing
- On deployment of an agent with latest main I was seeing
```
oc logs -f pod/weather-service-587996f5bb-99srp -c kagenti-client-registration -n <namespace>
Traceback (most recent call last):
File "/app/client_registration.py", line 92, in <module>
write_secret(keycloak_admin, internal_client_id, client_name, secret_file="/shared/secret.txt")
TypeError: write_secret() got an unexpected keyword argument 'secret_file'
```

:bug::art: Update client registration variable

---

kagenti/ui/lib/build_utils.py

This PR adds new UI section to the import form that allows users to configure custom service ports for K8s pods. This enables port override functionality directly from the UI, giving users more control over their agent/tool deployments
Fixes #234

:sparkles:  Ad k8s Pod Configuration UI for Service Ports Override

---

charts/kagenti/.secrets_template.yaml
charts/kagenti/templates/agent-namespaces.yaml
charts/kagenti/values.yaml
docs/ocp/openshift-install.md

- Add quay.io secret generation from token/user
- Update example for  latest tagged reference and link to tagged version.

📖  update ref to latest tagged version
